language: python
os:   linux
dist: bionic

git:
  submodules: false

install:
  - sudo apt update
  - sudo apt install gdb-multiarch binutils-riscv64-unknown-elf
  - pip install -r requirements.txt

script:
  - pytest
