language: python
os:   linux
dist: bionic

git:
  submodules: false

install:
  - sudo apt update
  - sudo apt install gdb-multiarch
  - pip install -r engine/src/requirements.txt
  
script:
  - pytest
  
