language: python
os:   linux
dist: bionic

git:
  submodules: false

install:
  - sudo apt update
  - sudo apt install gdb-multiarch ninja-build
  - pip install -r engine/src/requirements.txt
  
script:
  - cd engine
  - git submodule update --init
  - ./scripts/patch.sh
  - cd qemu 
  - ./configure --target-list=riscv64-softmmu,riscv32-softmmu
  - make -j
  - sudo make install
  - cd ../src
  - pytest
  
